ex2: main_2.o inverte_array.o manipula_array.o
	gcc main_2.o inverte_array.o manipula_array.o -o ex2
main_2.o: main_2.c
	gcc main_2.c -c
inverte_array.o: inverte_array.s
	gcc inverte_array.s -c
manipula_array.o: manipula_array.s
	gcc manipula_array.s -c
